// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBFqk1wPftJaazmOw_2Atx8OkpnerCL-k',
    appId: '1:924542924152:web:d4a06aad61bdd0afd0048d',
    messagingSenderId: '924542924152',
    projectId: 'optiodyssey',
    authDomain: 'optiodyssey.firebaseapp.com',
    storageBucket: 'optiodyssey.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4tR4pthcOl_LIg2KXsbF-SXYYfdc5dXI',
    appId: '1:924542924152:android:4dcd4173a67d671bd0048d',
    messagingSenderId: '924542924152',
    projectId: 'optiodyssey',
    storageBucket: 'optiodyssey.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWP1ZGHz7eyrsDdqmkrn1iTbb1FQMY_Gs',
    appId: '1:924542924152:ios:892d684e1530f688d0048d',
    messagingSenderId: '924542924152',
    projectId: 'optiodyssey',
    storageBucket: 'optiodyssey.appspot.com',
    iosClientId: '924542924152-fni3k38a5bo5r382evqvq20a2hb9f2es.apps.googleusercontent.com',
    iosBundleId: 'dev.arnovdvyver.routingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWP1ZGHz7eyrsDdqmkrn1iTbb1FQMY_Gs',
    appId: '1:924542924152:ios:892d684e1530f688d0048d',
    messagingSenderId: '924542924152',
    projectId: 'optiodyssey',
    storageBucket: 'optiodyssey.appspot.com',
    iosClientId: '924542924152-fni3k38a5bo5r382evqvq20a2hb9f2es.apps.googleusercontent.com',
    iosBundleId: 'dev.arnovdvyver.routingApp',
  );
}
